services:
  backend:
    build:
      context: ./backend
    container_name: projeto-2-backend
    ports:
      - "3002:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - cin_proxy

  frontend:
    build:
      context: ./frontend
    container_name: projeto-2-frontend
    volumes:
      - /opt/docker/frontends/projeto2:/output
    depends_on:
      - backend
    restart: "no"

networks:
  cin_proxy:
    external: true